
const navigationConfig = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        icon: 'home',
        type: 'item',
        subMenu: [],
    },
    {
        key: 'leads',
        path: '/leads',
        title: 'Leads',
        icon: 'users',
        type: 'item',
        subMenu: [],
    },
    {
        key: 'campaigns',
        path: '/campaigns',
        title: 'Campaigns',
        icon: 'megaphone',
        type: 'item',
        subMenu: [],
    },
    {
        key: 'analytics',
        path: '/analytics',
        title: 'Analytics',
        icon: 'chart-bar',
        type: 'item',
        subMenu: [],
    },
    {
        key: 'company',
        path: '',
        title: 'Company',
        icon: 'building',
        type: 'collapse',
        subMenu: [
            {
                key: 'company.overview',
                path: '/company/overview',
                title: 'Overview',
                icon: 'eye',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.employees',
                path: '/company/employees',
                title: 'Employees',
                icon: 'users',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.territories',
                path: '/company/territories',
                title: 'Territories',
                icon: 'map',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.permissions',
                path: '/company/permissions',
                title: 'Permissions',
                icon: 'shield',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.billing',
                path: '/company/billing',
                title: 'Billing',
                icon: 'credit-card',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.branding',
                path: '/company/branding',
                title: 'Branding',
                icon: 'paint-brush',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.analytics',
                path: '/company/analytics',
                title: 'Analytics',
                icon: 'chart-pie',
                type: 'item',
                subMenu: [],
            },
            {
                key: 'company.notifications',
                path: '/company/notifications',
                title: 'Notifications',
                icon: 'bell',
                type: 'item',
                subMenu: [],
            },
        ],
    },
    {
        key: 'profile',
        path: '/profile',
        title: 'Profile',
        icon: 'user',
        type: 'item',
        subMenu: [],
    },
]

export default navigationConfig 